wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1637675366
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 13
      - 16
      4: 3.6.13
      5: 0.12.7
      8:
      - 5
batch_size:
  desc: null
  value: 32
ci:
  desc: null
  value: 0
client_num_in_total:
  desc: null
  value: 1000
client_num_per_round:
  desc: null
  value: 50
client_optimizer:
  desc: null
  value: sgd
comm_round:
  desc: null
  value: 200
data_dir:
  desc: null
  value: ./../../../data/FederatedEMNIST/datasets
dataset:
  desc: null
  value: femnist
epochs:
  desc: null
  value: 5
frequency_of_the_test:
  desc: null
  value: 5
gpu:
  desc: null
  value: 3
interver:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.03
model:
  desc: null
  value: cnn
name:
  desc: null
  value: FedEmnist_client
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero
wd:
  desc: null
  value: 0.001
